drop table if exists board CASCADE;
create table board
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    created_at datetime null default current_timestamp(),
    updated_at datetime null default current_timestamp() on update current_timestamp(),
    primary key (id)
);
