spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test
  quartz:
    jdbc:
      initialize-schema: never
      schema:
    job-store-type: jdbc
    properties:
      # ???? ???? ??? ?? ID ??
      org.quartz.scheduler.instanceId: AUTO

      # quartz ?????? ??? dataSource ??
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mysql://localhost:3306/test
      org.quartz.dataSource.quartzDataSource.driver: com.mysql.cj.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: 123
      org.quartz.dataSource.quartzDataSource.provider: hikaricp

      # quartz dataSource? ??? ??? ???? ??
      org.quartz.jobStore.dataSource: quartzDataSource

      # jobStroe ??
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.useProperties: false
      # quartz ???? ??? ? prefix (default QRTZ_)
      #org.quartz.jobStore.tablePrefix=QRTZ_
      # ??? ??? ?? ??? ?? ?? (default 60000)
      #org.quartz.jobStore.misfireThreshold=60000
      # ???? ? ???? ?? (default 15000)
      #org.quartz.jobStore.clusterCheckinInterval=15000
      # ????? ?? ?? ?? (default false)
      #org.quartz.jobStore.isClustered=true

      # threadPool ??
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      # Thread ?? ?? (1 ~ 100) (default -1) (???? Job? ??? 1??? ?? ??? ?? ?? Job?? ???? 50, 100?? ??? ?)
      #org.quartz.threadPool.threadCount=10
      # Thread ???? ?? (1 ~ 10) (default 5)
      #org.quartz.threadPool.threadPriority=5

